### ISSUE TITLE
Cannot compile in XCode 9.1

### ISSUE THREAD

**Issue by Gloix** [uber/rides-ios-sdk#195]
When I try to compile UberRides 0.7 I get compilation errors such as:

    Type 'UILayoutPriority' (aka 'Float') has no member 'defaultHigh'
    Type 'NSAttributedStringKey' (aka 'NSString') has no member 'paragraphStyle'
    Type 'NSAttributedStringKey' (aka 'NSString') has no member 'font'
    'accessTokenWasUnauthorizedOnPreviousAttempt' is inaccessible due to 'private' protection level
    ...

What am I doing wrong?

**Comment by edjiang** [comment]
^^ Glad you got it resolved!
